## Concept of list
### * here i can get mulitiple inputs in a structured way 
    * it works in 1D way  if fully rows(or) fully coloumn
    *it accepts float,int all so it is hetrogeneous datastructure

In [6]:
store=["pen","pencil","scale","slade"] #here i can get multiple inputs

In [7]:
store

['pen', 'pencil', 'scale', 'slade']

In [8]:
type(store)

list

In [9]:
store=["pen","pencil","scale","slade","pencil"]

In [10]:
store

['pen', 'pencil', 'scale', 'slade', 'pencil']

#### so list accepts duplicates or repeated values

In [12]:
print(store[2])#here we use indexing [] concept this is not only for list

scale

In [22]:
store[-4:-2]

['pencil', 'scale']

In [26]:
store[1]="eraser" #so here we can change the value so it is mutable

In [24]:
print(store)

['pen', 'eraser', 'scale', 'slade', 'pencil']

## sets datastructures

In [30]:
store_1= set()

In [28]:
type(store_1)

set

In [33]:
store_1={"pen","pencil","scale","slade","pencil"}

In [34]:
store_1

{'pen', 'pencil', 'scale', 'slade'}

In [35]:
store_1[1]

TypeError: 'set' object is not subscriptable

### 'set' object is not subscriptable  
  -- so we can't indexing and slicing
  -- it is mutable

In [37]:
store_1.add("sharpner")

In [38]:
store_1

{'pen', 'pencil', 'scale', 'sharpner', 'slade'}

In [42]:
store_1.update()

In [43]:
store_1

{'pen', 'pencil', 'scale', 'sharpner', 'slade'}

In [44]:
store_1.add("box")

In [45]:
store_1

{'box', 'pen', 'pencil', 'scale', 'sharpner', 'slade'}

In [48]:
store_1.discard("sharpner")

In [49]:
store_1

{'box', 'pen', 'pencil', 'scale', 'slade'}

### TUPLES

* it is hertrogenious
* *it is accept duplicates
* it can index and slicing the elements but it cant change
* it is immutable( #we can see the element but we cant change that)

In [1]:
flower_shop=()

In [2]:
type(flower_shop)

tuple

In [3]:
flower_shop=('rose', 'jasmine', 'lavendar', 'hibicus', 'sunflower')

In [5]:
flower_shop[-4:-1]

('jasmine', 'lavendar', 'hibicus')

In [6]:
flower_shop["rose"]="pk"

TypeError: 'tuple' object does not support item assignment

## dictionary

In [23]:
## it is called key value pair datastructure
##it allows the duplicate(key) but it is updated by the second entry

In [39]:
flower_shop_1={'rose':[3,4], 'jasmine':[5], 'lavendar':[7], 'hibicus':[3], 'sunflower':[1],"rose":[8],"rose":[4]}

In [40]:
type(flower_shop_1)

dict

In [41]:
flower_shop_1

{'rose': [4],
 'jasmine': [5],
 'lavendar': [7],
 'hibicus': [3],
 'sunflower': [1]}

In [42]:
import pandas as pd

In [43]:
pd.DataFrame(flower_shop_1)

   rose  jasmine  lavendar  hibicus  sunflower
0     4        5         7        3          1

In [37]:
student_mark={"name":['viru','bha','sha','yan'],"marks":[20,30,40,50]}

In [38]:
pd.DataFrame(student_mark)

   name  marks
0  viru     20
1   bha     30
2   sha     40
3   yan     50

# The end