In [1]:
import pandas as pd
import seaborn as sns

In [2]:
Movie_Db = pd.read_csv('Movie.csv')
Movie_Db

      userId             movie  rating
0          3  Toy Story (1995)     4.0
1          6  Toy Story (1995)     5.0
2          8  Toy Story (1995)     4.0
3         10  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
...      ...               ...     ...
8987    7087  GoldenEye (1995)     3.0
8988    7088  GoldenEye (1995)     1.0
8989    7105  GoldenEye (1995)     2.0
8990    7113  GoldenEye (1995)     3.0
8991    7117  GoldenEye (1995)     3.0

[8992 rows x 3 columns]

### Data Cleaning

In [3]:
Movie_Db.isna().sum()

userId    0
movie     0
rating    0
dtype: int64

In [4]:
print(Movie_Db.duplicated().sum())

0

### Data Understanding

## Co-relation Based Recommanding

In [49]:
pivot_table_Db = pd.pivot_table(data =Movie_Db,values='rating',index='movie',columns='userId',).fillna(0)
pivot_table_Db.columns = Movie_Db['userId'].unique()
pivot_table_Db
pivot_table_Db.iloc[:10,:10]
pivot_table_Db.corr().round(1)
#sns.heatmap(data = pivot_table_Db.corr().round(1).iloc[:10,:10],annot = True,cmap='Blues')

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,1.0,-0.1,-0.1,-0.2,1.0,-0.2,-0.2,-0.3,-0.1,-0.2,...,-0.1,-0.1,1.0,0.7,-0.2,-0.1,-0.2,-0.4,-0.1,0.5
6,-0.1,1.0,-0.1,-0.2,-0.1,0.3,0.7,0.6,-0.1,-0.2,...,-0.1,-0.1,-0.1,-0.2,-0.2,-0.1,-0.2,0.4,-0.1,-0.2
8,-0.1,-0.1,1.0,-0.2,-0.1,0.6,-0.2,0.4,1.0,0.9,...,-0.1,1.0,-0.1,0.7,-0.2,-0.1,0.7,0.4,1.0,0.6
10,-0.2,-0.2,-0.2,1.0,-0.2,-0.3,-0.2,0.5,-0.2,0.2,...,0.8,-0.2,-0.2,-0.2,1.0,-0.2,-0.2,0.5,-0.2,-0.3
11,1.0,-0.1,-0.1,-0.2,1.0,-0.2,-0.2,-0.3,-0.1,-0.2,...,-0.1,-0.1,1.0,0.7,-0.2,-0.1,-0.2,-0.4,-0.1,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,-0.1,-0.1,-0.1,-0.2,-0.1,-0.2,-0.2,-0.3,-0.1,-0.2,...,-0.1,-0.1,-0.1,-0.2,-0.2,1.0,0.6,-0.4,-0.1,-0.2
7070,-0.2,-0.2,0.7,-0.2,-0.2,0.3,-0.2,0.1,0.7,0.6,...,-0.2,0.7,-0.2,0.4,-0.2,0.6,1.0,0.0,0.7,0.3
7080,-0.4,0.4,0.4,0.5,-0.4,0.5,0.4,0.8,0.4,0.4,...,0.2,0.4,-0.4,0.0,0.5,-0.4,0.0,1.0,0.4,0.1
7087,-0.1,-0.1,1.0,-0.2,-0.1,0.6,-0.2,0.4,1.0,0.9,...,-0.1,1.0,-0.1,0.7,-0.2,-0.1,0.7,0.4,1.0,0.6
7105,0.5,-0.2,0.6,-0.3,0.5,0.7,0.2,-0.1,0.6,0.4,...,-0.2,0.6,0.5,0.8,-0.3,-0.2,0.3,0.1,0.6,1.0

In [50]:
Movie_Db[ (Movie_Db['userId'] == 3) | (Movie_Db['userId'] == 11) ]

      userId             movie  rating
0          3  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
7446      11  GoldenEye (1995)     2.5

## Distance Based Recommendation

### Euculidion Approach

In [51]:
from sklearn.metrics import pairwise_distances

In [52]:
pivot_table_Db_Distance = pd.pivot_table(data =Movie_Db,values='rating',index='userId',columns='movie',).fillna(0)
pivot_table_Db_Distance.columns  = Movie_Db['movie'].unique()
pivot_table_Db_Distance.index    = Movie_Db['userId'].unique()
pivot_table_Db_Distance.iloc[:10,:10]
#pivot_table_Db.corr().round(1)

,Toy Story (1995),Jumanji (1995),Grumpier Old Men (1995),Waiting to Exhale (1995),Father of the Bride Part II (1995),Heat (1995),Sabrina (1995),Tom and Huck (1995),Sudden Death (1995),GoldenEye (1995)
3,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
10,0.0,4.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,3.0,0.0,0.0,5.0,0.0,0.0,5.0,0.0
13,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0
14,0.0,4.0,5.0,3.0,0.0,0.0,0.0,0.0,4.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
19,0.0,2.5,0.0,0.0,0.0,0.0,0.0,0.0,4.5,0.0

In [53]:
distance_corr= pd.DataFrame(pairwise_distances(pivot_table_Db_Distance,metric='euclidean'))
distance_corr.columns  = Movie_Db['userId'].unique()
distance_corr.index    = Movie_Db['userId'].unique()
distance_corr.iloc[:10,:10].round(2)

      3     6     8     10    11    12    13    14    16    19
3   0.00  5.32  5.32  6.10  0.50  8.44  5.50  8.85  5.32  6.22
6   5.32  0.00  5.66  6.40  5.00  7.14  3.16  6.48  5.66  6.52
8   5.32  5.66  0.00  6.40  5.00  5.92  5.83  7.07  0.00  2.55
10  6.10  6.40  6.40  0.00  5.83  9.17  6.56  6.40  6.40  5.61
11  0.50  5.00  5.00  5.83  0.00  8.25  5.20  8.66  5.00  5.96
12  8.44  7.14  5.92  9.17  8.25  0.00  5.39  7.42  5.92  6.36
13  5.50  3.16  5.83  6.56  5.20  5.39  0.00  7.35  5.83  6.67
14  8.85  6.48  7.07  6.40  8.66  7.42  7.35  0.00  7.07  6.04
16  5.32  5.66  0.00  6.40  5.00  5.92  5.83  7.07  0.00  2.55
19  6.22  6.52  2.55  5.61  5.96  6.36  6.67  6.04  2.55  0.00

In [ ]:
distance_corr= pd.DataFrame(pairwise_distances(pivot_table_Db_Distance,metric='euclidean'))
distance_corr.columns  = Movie_Db['userId'].unique()
distance_corr.index    = Movie_Db['userId'].unique()
distance_corr.iloc[:10,:10].round(2)